### ISSUE TITLE
Authenticate failed after previously working

### ISSUE THREAD

**Issue by svedev0** [KusoKaihatsuSha/appgotapo#6]
The following command was working fine up until about 3 days ago:

```
.\appgotapo.exe -host="192.168.x.x" -u="admin" -p="tapoPassword" -do="move:10_0"
```

"tapoPassword" in the command above is my Tapo cloud account's password and not the local RTSP account's password.

The camera's firmware has not been updated recently and the command was not modified.

Since the issue started, the following error is displayed any time the command is run.

To clarify, this exact setup has been working perfectly until 3 days ago.

```
Authenticate failed. Try use another cred. login - "admin", password - your password in Tapo account.
App will be trying with "admin" with next operation(if your pass on rtsp equal pass your account). If next operation exist.
panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
github.com/KusoKaihatsuSha/gotapo.(*Tapo).getDevice(0xc0000e6000)
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1677 +0x3af
github.com/KusoKaihatsuSha/gotapo.Connect({0xc0000b004e, 0xc}, {0xc00009c09b, 0x5}, {0xc0000b0063, 0x10})
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1371 +0x159
main.main.func1({0xc0000b004e?, 0x0?})
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:37 +0x45
created by main.main in goroutine 1
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:36 +0x2d8
```

**System information:**
Computer:
Windows 11 Pro 23H2 build 22631.3527
appgotapo v1.0.5 amd64 (unmodified release file)
Windows Terminal - Default command prompt profile

Camera:
Tapo C200 v3
Firmware 1.3.13 build 240327 Rel.63336n(4555)

**Comment by svedev0** [comment]
Edit:
My Tapo cloud account's password is not the same as my local RTSP account's password.

Connecting to- and viewing the RTSP stream using the local RTSP account credentials is still working.

**Comment by KusoKaihatsuSha** [comment]
**Hello!**
It's problem with TP-Link side - company added step with TP-Link Cloud token verify.
(The update apparently follows a canary principle, so it appeared to users at different times).

But GitHub Community became known the information about TP-Link plans - organize API with getting cloud token. However...plan not have any exact date of realize.

Long ticket about it in GitHub Community: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551

At the moment I'm inclined to wait for something official from the TP-Link. Manipulating with the TP-Link Сloud token may lead to legal uncertainties or blocks.


One way (if possible):
Try to reset the camera to factory settings (higher than build 230921)
and block internet access to the camera.

Other way (if possible):
Downgrade the firmware, where been insecure authorize, such as 1.1.12.

https://github.com/nervous-inhuman/tplink-tapo-c200-re/issues/4
https://github.com/tapo-firmware/Directory/blob/main/all_keys.txt

**Comment by svedev0** [comment]
Hi!

Thanks for taking the time to share this information. I have now read and caught up on the issue you linked and some similar ones.

I tried resetting the camera several times but this did not help. Blocking internet access to the camera did not change anything.

I then tried downgrading the firmware to 1.3.0 from [this url](http://download.tplinkcloud.com/firmware/Tapo_C200v3_en_1.3.0_Build_220909_Rel.43466n_u_1670296039976.bin) following [DrmnSamoLiu's guide](https://github.com/nervous-inhuman/tplink-tapo-c200-re/issues/4). **This solved the issue**. However, this is not an ideal solution going forward. Hopefully, TP-Link/Tapo will fix this issue soon.

**Comment by KusoKaihatsuSha** [comment]
Information update:
[TP-LINK does not confirm the use of cloud tokens, but promises to fix something in the new updates.](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2363817573)

**Comment by svedev0** [comment]
Excellent news about the app updates. Thank you for sharing. I have stayed on firmware version 1.3.0 and so far it is still working fine for me, but new updates are always nice.

**Comment by PhotonPAPA** [comment]
I also have started to have this issue. 

This is the script I have always used successfully:

mode con: cols=38 lines=29
@echo off
echo .
echo ......................................
echo :    Switching OFF IR Night Mode     :
echo :....................................:
echo .
C:\Users\willi\Documents\NINA\Scripts\appgotapo_windows_amd64 -host=192.168.1.85 -u admin -p 88888777 -do "night_off"
C:\Users\willi\Documents\NINA\Scripts\appgotapo_windows_amd64 -host=192.168.1.180 -u admin -p 88888777 -do "night_off"
echo ......................................
echo .
echo ......................................
echo :      IR Night Mode Now OFF         :
echo :....................................:
timeout /t 4 /nobreak >nul



And this is now this is the error I receive:

.
......................................
:    Switching OFF IR Night Mode     :
:....................................:
.
Authenticate failed. Try use another cred. login - "admin", password - your password in Tapo account.
App will be trying with "admin" with next operation(if your pass on rtsp equal pass your account). If next operation exist.
panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
github.com/KusoKaihatsuSha/gotapo.(*Tapo).getDevice(0xc00013c000)
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1677 +0x3af
github.com/KusoKaihatsuSha/gotapo.Connect({0xc000010126, 0xc}, {0xc00000a108, 0x5}, {0xc00000a140, 0xb})
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1371 +0x159
main.main.func1({0xc000010126?, 0x0?})
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:37 +0x45
created by main.main in goroutine 1
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:36 +0x2d8
Authenticate failed. Try use another cred. login - "admin", password - your password in Tapo account.
App will be trying with "admin" with next operation(if your pass on rtsp equal pass your account). If next operation exist.
panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
github.com/KusoKaihatsuSha/gotapo.(*Tapo).getDevice(0xc00013c000)
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1677 +0x3af
github.com/KusoKaihatsuSha/gotapo.Connect({0xc000010126, 0xd}, {0xc00000a108, 0x5}, {0xc00000a140, 0xb})
        C:/Users/skald/go/pkg/mod/github.com/!kuso!kaihatsu!sha/gotapo@v1.0.5/gotapo.go:1371 +0x159
main.main.func1({0xc000010126?, 0x0?})
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:37 +0x45
created by main.main in goroutine 1
        c:/Users/skald/Downloads/_camtest/appgotapo/main.go:36 +0x2d8
......................................
.
......................................
:      IR Night Mode Now OFF         :
:....................................:


My current firmware is 1.3.11 and I previously did not have this issue. My Tapo app says there is a firmware update available to 1.3.16. Will updating the firmware resolve the issue?

**Comment by KusoKaihatsuSha** [comment]
In addition to the firmware, please specify the device name. It is likely that updating the device firmware will not solve the problem. I will prepare a new version.

**Comment by PhotonPAPA** [comment]
I think it’s working now. I had to enable Third Party Compatibility in the
Tapo app.

Thank you for coming back to me. If it stops working. I’ll let you know.
